// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppProvider: typeof import('./src/components/template/AppProvider.vue')['default']
    DialogContent: typeof import('./src/components/organisms/DialogContent.vue')['default']
    LoadingBar: typeof import('./src/components/organisms/LoadingBar.vue')['default']
    MessageContent: typeof import('./src/components/organisms/MessageContent.vue')['default']
    NotificationContent: typeof import('./src/components/organisms/NotificationContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
